asciidoc -v for_translation_mastering-bitcoin_preface-open_fr_CA.asciidoc
asciidoc -v for_translation_mastering-bitcoin_preface_fr_CA.asciidoc
asciidoc -v for_translation_mastering-bitcoin_glossary-1_fr_CA.asciidoc

asciidoc -v for_translation_mastering-bitcoin_chapter-1_fr_CA.asciidoc
asciidoc -v for_translation_mastering-bitcoin_chapter-2_fr_CA.asciidoc
asciidoc -v for_translation_mastering-bitcoin_chapter-3_fr_CA.asciidoc
asciidoc -v for_translation_mastering-bitcoin_chapter-4_fr_CA.asciidoc
asciidoc -v for_translation_mastering-bitcoin_chapter-5_fr_CA.asciidoc
asciidoc -v for_translation_mastering-bitcoin_chapter-6_fr_CA.asciidoc
asciidoc -v for_translation_mastering-bitcoin_chapter-7_fr_CA.asciidoc
asciidoc -v for_translation_mastering-bitcoin_chapter-8_fr_CA.asciidoc
asciidoc -v for_translation_mastering-bitcoin_chapter-9_fr_CA.asciidoc
asciidoc -v for_translation_mastering-bitcoin_chapter-10_fr_CA.asciidoc
asciidoc -v for_translation_mastering-bitcoin_ch11_fr_CA.asciidoc
asciidoc -v for_translation_mastering-bitcoin_ch12_fr_CA.asciidoc

asciidoc -v for_translation_mastering-bitcoin_appdx-bitcoinwhitepape.asciidoc_fr_CA.txt
asciidoc -v for_translation_mastering-bitcoin_appendix-script-ops_fr_CA.asciidoc
asciidoc -v for_translation_mastering-bitcoin_appendix-bips_fr_CA.asciidoc
asciidoc -v for_translation_mastering-bitcoin_appdx-bitcor.asciidoc_fr_CA.txt
asciidoc -v for_translation_mastering-bitcoin_appendix-pycoin_fr_CA.asciidoc
asciidoc -v for_translation_mastering-bitcoin_appendix-bx_fr_CA.asciidoc
