[preface]
[[preface]]
== Préface

Ce livre est une collaboration entre Andreas M. Antonopoulos et le Dr Gavin Wood. Une série de coïncidences heureuses a réuni ces deux auteurs dans un effort qui a galvanisé des centaines de contributeurs pour produire ce livre, dans le meilleur esprit de l&#39;open source et de la culture creative commons.

Gavin souhaitait écrire un livre qui développait le Livre jaune (sa description technique du protocole Ethereum) depuis un certain temps, principalement pour l&#39;ouvrir à un public plus large que ne le permettait le document original infusé de lettres grecques.

Des plans étaient en cours - un éditeur avait été trouvé - lorsque Gavin a parlé à Andreas, qu&#39;il connaissait depuis le tout début de son mandat chez Ethereum en tant que personnalité notable dans l&#39;espace.

Andreas avait récemment publié la première édition de son livre _Mastering Bitcoin_ (O&#39;Reilly), qui est rapidement devenu le guide technique faisant autorité sur le Bitcoin et les cryptomonnaies. Presque aussitôt que le livre a été publié, ses lecteurs ont commencé à lui demander : &quot;Quand écriras-tu &#39;Mastering Ethereum&#39; ?&quot; Andreas envisageait déjà son prochain projet et a trouvé qu&#39;Ethereum était un sujet technique convaincant.

Enfin, en mai 2016, Gavin et Andreas se trouvaient par coïncidence dans la même ville au même moment. Ils se sont retrouvés autour d&#39;un café pour discuter de travailler ensemble sur le livre. Andreas et Gavin étant tous deux des adeptes du paradigme open source, ils se sont tous deux engagés à en faire un effort collaboratif, publié sous une licence Creative Commons. Heureusement, l&#39;éditeur, O&#39;Reilly Media, était heureux d&#39;être d&#39;accord, et le projet _Mastering Ethereum_ a été officiellement lancé.

=== Comment utiliser ce livre

Le livre est destiné à servir à la fois de manuel de référence et d&#39;exploration d&#39;Ethereum de bout en bout. Les deux premiers chapitres offrent une introduction douce, adaptée aux utilisateurs novices, et les exemples de ces chapitres peuvent être complétés par toute personne ayant un peu de compétence technique. Ces deux chapitres vous donneront une bonne compréhension des bases et vous permettront d&#39;utiliser les outils fondamentaux d&#39;Ethereum. &lt;<ethereum_clients_chapter>&gt; et au-delà sont destinés principalement aux programmeurs et incluent de nombreux sujets techniques et exemples de programmation.

Pour servir à la fois de manuel de référence et de récit complet sur Ethereum, le livre contient inévitablement des doublons. Certains sujets, tels que le _gaz_, doivent être introduits suffisamment tôt pour que le reste des sujets ait un sens, mais sont également examinés en profondeur dans leurs propres sections.

Enfin, l&#39;index du livre permet aux lecteurs de trouver facilement des sujets très précis et les sections pertinentes, par mot-clé.

[[intended_audience_sec]]
=== Public visé

(((&quot;audience visée&quot;)))Ce livre est principalement destiné aux codeurs. Si vous pouvez utiliser un langage de programmation, ce livre vous apprendra comment fonctionnent les chaînes de blocs de contrats intelligents, comment les utiliser et comment développer des contrats intelligents et des applications décentralisées avec eux. Les premiers chapitres conviennent également comme une introduction approfondie à Ethereum pour les non-codeurs.



[[conventinons_used_sec]]
=== Conventions utilisées dans ce livre

(((&quot;conventions typographiques&quot;)))Les conventions typographiques suivantes sont utilisées dans ce livre :

_Italic_:: Indique de nouveaux termes, URL, adresses e-mail, noms de fichiers et extensions de fichiers.

+Largeur constante+:: Utilisé pour les listes de programmes, ainsi que dans les paragraphes pour faire référence à des éléments de programme tels que des noms de variables ou de fonctions, des bases de données, des types de données, des variables d&#39;environnement, des instructions et des mots-clés.

**`Largeur constante en gras`**:: Affiche les commandes ou tout autre texte qui doit être saisi littéralement par l&#39;utilisateur.

_++Largeur constante en italique++_:: affiche le texte qui doit être remplacé par des valeurs fournies par l&#39;utilisateur ou des valeurs déterminées par le contexte.


[TIP]
====
Cette icône signifie un conseil ou une suggestion.
====

[NOTE]
====
Cette icône signifie une note générale.
====

[WARNING]
====
Cette icône indique un avertissement ou une mise en garde.
====

[[code_examples_sec]]
=== Exemples de codes

(((&quot;exemples de code, obtention et utilisation&quot;)))Les exemples sont illustrés dans Solidity, Vyper et JavaScript, et en utilisant la ligne de commande d&#39;un système d&#39;exploitation de type Unix. Tous les extraits de code sont disponibles dans le référentiel GitHub sous le sous-répertoire _code_. Fourchez le code du livre, essayez les exemples de code ou soumettez des corrections via GitHub : https://github.com/ethereumbook/ethereumbook.

Tous les extraits de code peuvent être répliqués sur la plupart des systèmes d&#39;exploitation avec une installation minimale de compilateurs, d&#39;interpréteurs et de bibliothèques pour les langages correspondants. Si nécessaire, nous fournissons des instructions d&#39;installation de base et des exemples étape par étape de la sortie de ces instructions.

Certains des extraits de code et des sorties de code ont été reformatés pour l&#39;impression. Dans tous ces cas, les lignes ont été séparées par une barre oblique inverse (+\+), suivie d&#39;un caractère de saut de ligne. Lors de la transcription des exemples, supprimez ces deux caractères et rejoignez les lignes à nouveau et vous devriez voir des résultats identiques à ceux présentés dans l&#39;exemple.

Tous les extraits de code utilisent des valeurs réelles et des calculs lorsque cela est possible, de sorte que vous pouvez construire d&#39;exemple en exemple et voir les mêmes résultats dans n&#39;importe quel code que vous écrivez pour calculer les mêmes valeurs. Par exemple, les clés privées et les clés et adresses publiques correspondantes sont toutes réelles. Les exemples de transactions, de contrats, de blocs et de références de chaîne de blocs ont tous été introduits dans la chaîne de blocs Ethereum actuelle et font partie du grand livre public, vous pouvez donc les consulter.


(((&quot;attribution&quot;)))Nous apprécions, mais n&#39;exigeons pas, l&#39;attribution. Une attribution comprend généralement le titre, l&#39;auteur, l&#39;éditeur, l&#39;ISBN et le droit d&#39;auteur. Par exemple : « __Mastering Ethereum__ par Andreas M. Antonopoulos et le Dr Gavin Wood. Copyright 2019 The Ethereum Book LLC et Gavin Wood&quot;

(((&quot;licences open source&quot;)))__Mastering Ethereum__ est proposé sous la licence internationale Creative Commons Attribution-ShareAlike (CC BY SA 4.0).


=== Références aux entreprises et aux produits

Toutes les références aux entreprises et aux produits sont destinées à des fins éducatives, de démonstration et de référence. Les auteurs ne cautionnent aucune des entreprises ou des produits mentionnés. Nous n&#39;avons testé le fonctionnement ou la sécurité d&#39;aucun des produits, projets ou segments de code présentés dans ce livre. Utilisez-les à vos risques et périls!

[[ethereum_sdresses_and_transactions_sec]]
=== Adresses et transactions Ethereum dans ce livre

(((&quot;chaîne de blocs&quot;,&quot;avertissements et précautions&quot;)))(((&quot;clés et adresses&quot;, seealso=&quot;cryptographie; clés privées; clés publiques&quot;)))(((&quot;codes QR&quot;)))(( (&quot;transactions&quot;,&quot;avertissements et mises en garde&quot;)))(((&quot;avertissements et mises en garde&quot;,&quot;lors de l&#39;utilisation de matériel de test et d&#39;exemple apparaissant dans le livre&quot;)))Les adresses Ethereum, les transactions, les clés, les codes QR et les données de la chaîne de blocs utilisés dans ce livre sont, pour la plupart, réels. Cela signifie que vous pouvez parcourir la chaîne de blocs, regarder les transactions proposées en exemple, les récupérer avec vos propres scripts ou programmes, etc.

(((&quot;avertissements et précautions&quot;, &quot;évitez d&#39;envoyer de l&#39;argent aux adresses figurant dans le livre&quot;)))Cependant, notez que les clés privées utilisées pour construire les adresses imprimées dans ce livre ont été &quot;brûlées&quot;. Cela signifie que si vous envoyez de l&#39;argent à l&#39;une de ces adresses, l&#39;argent sera perdu pour toujours ou (plus probablement) approprié, puisque toute personne qui lit le livre peut le prendre en utilisant les clés privées imprimées ici.

[WARNING]
====
N&#39;ENVOYEZ D&#39;ARGENT A AUCUNE DES ADRESSES DANS CE LIVRE. Votre argent sera pris par un autre lecteur, ou perdu à jamais.
====

==== Contacter Andreas

Vous pouvez contacter Andreas M. Antonopoulos sur son site personnel :
link:$$https://antonopoulos.com/$$[]

Abonnez-vous à la chaîne d&#39;Andreas sur YouTube :
link:$$https://www.youtube.com/aantonop$$[]

Aimez la page d&#39;Andreas sur Facebook :
link:$$https://www.facebook.com/AndreasMAntonopoulos$$[]

Suivez Andreas sur Twitter :
link:$$https://twitter.com/aantonop$$[]

Connectez-vous avec Andreas sur LinkedIn :
link:$$https://linkedin.com/company/aantonop$$[]

Andreas tient également à remercier tous les mécènes qui soutiennent son travail par des dons mensuels. Vous pouvez soutenir Andreas sur Patreon à
link:$$https://patreon.com/aantonop$$[].


==== Contacter Gavin

Vous pouvez contacter le Dr Gavin Wood sur son site personnel :
link:$$http://gavwood.com/$$[]

Suivez Gavin sur Twitter :
link:$$https://twitter.com/gavofyork$$[]

Gavin traîne généralement dans le Polkadot Watercooler sur Riot.im :
link:$$http://bit.ly/2xciG68$$[]


[[acknowledgments_sec]]
=== Remerciements par Andreas

Je dois mon amour des mots et des livres à ma mère, Theresa, qui m&#39;a élevé dans une maison avec des livres tapissant tous les murs. Ma mère m&#39;a également acheté mon premier ordinateur en 1982, bien qu&#39;elle se décrive comme une technophobe. Mon père, Menelaos, un ingénieur civil qui a publié son premier livre à 80 ans, est celui qui m&#39;a enseigné la pensée logique et analytique et l&#39;amour de la science et de l&#39;ingénierie.

Merci à tous de m&#39;avoir soutenu tout au long de ce parcours.

=== Remerciements par Gavin

Ma mère m&#39;a procuré mon premier ordinateur chez un voisin quand j&#39;avais 9 ans, sans quoi mes progrès techniques auraient sans doute été amoindris. Je lui dois aussi ma peur de l&#39;électricité depuis mon enfance et je dois reconnaître Trevor et mes grands-parents, qui ont accompli le grave devoir de &quot;me regarder le brancher&quot; à maintes reprises, et sans qui ledit ordinateur aurait été inutile. Je dois également reconnaître les différents éducateurs que j&#39;ai eu la chance d&#39;avoir tout au long de ma vie, du dit voisin Sean (qui m&#39;a appris mon premier programme informatique), à M. Quinn, mon professeur d&#39;école primaire, qui m&#39;a aidé à faire plus de programmation et moins d&#39;histoire, grâce à des enseignants du secondaire comme Richard Furlong-Brown, qui m&#39;ont arrangé pour que je fasse plus de programmation et moins de rugby.

Je dois remercier la mère de mes enfants, Jutta, pour son soutien continu, et les nombreuses personnes dans ma vie, amis nouveaux et anciens, qui me gardent, grosso modo, sain d&#39;esprit. Enfin, une énorme cuillerée de remerciements doit aller à Aeron Buchanan, sans qui les cinq dernières années de ma vie n&#39;auraient jamais pu se dérouler comme elles l&#39;ont fait et sans le temps, le soutien et les conseils de qui ce livre ne serait pas en aussi bon état tel quel.


include::github_contrib.asciidoc[]

=== Sources

Ce livre fait référence à diverses sources publiques et sous licence libre :

https://github.com/ethereum/vyper/blob/master/README.md::
La licence MIT (MIT)


https://vyper.readthedocs.io/en/latest/::
La licence MIT (MIT)


https://solidity.readthedocs.io/en/v0.4.21/common-patterns.html::
La licence MIT (MIT)

https://arxiv.org/pdf/1802.06038.pdf::
Arxiv Non-Exclusive-Distribution

https://github.com/ethereum/solidity/blob/release/docs/contracts.rst#inheritance::
La licence MIT (MIT)

https://github.com/trailofbits/evm-opcodes::
Apache 2.0

https://github.com/ethereum/EIPs/::
Creative Commons CC0


https://blog.sigmaprime.io/solidity-security.html::
Creative Commons CC BY 4.0