[[vyper_chap]]
== Contrats intelligents et Vyper

(((&quot;Vyper&quot;, id=&quot;ix_08smart-contracts-vyper-asciidoc0&quot;, range=&quot;startofrange&quot;)))Vyper est un langage de programmation expérimental orienté contrat pour la machine virtuelle Ethereum qui s&#39;efforce de fournir une auditabilité supérieure, en permettant aux développeurs de produire plus facilement du code intelligible. En fait, l&#39;un des principes de Vyper est de rendre pratiquement impossible pour les développeurs d&#39;écrire du code trompeur.

Dans ce chapitre, nous examinerons les problèmes courants liés aux contrats intelligents, présenterons le langage de programmation de contrats Vyper et le comparerons à Solidity, en démontrant les différences.

=== Vulnérabilités et Vyper

https://arxiv.org/pdf/1802.06038.pdf[Une étude récente] (((&quot;vulnérabilités&quot;, seealso=&quot;sécurité ; attaques/vulnérabilités spécifiques&quot;)))(((&quot;Vyper&quot;,&quot;contracter les vulnérabilités et&quot; ))) a analysé près d&#39;un million de contrats intelligents Ethereum déployés et a constaté que nombre de ces contrats contenaient de graves vulnérabilités. Au cours de leur analyse, les chercheurs ont défini trois catégories de base de vulnérabilités en trace:

Contrats suicidaires:: Contrats intelligents qui peuvent être tués par des adresses arbitraires

Contrats cupides:: Contrats intelligents pouvant atteindre un état dans lequel ils ne peuvent pas libérer d&#39;ether

Contrats prodigues:: Contrats intelligents pouvant être conclus pour libérer de l&#39;ether à des adresses arbitraires

Les vulnérabilités sont introduites dans les contrats intelligents via le code. Il peut être fortement soutenu que ces vulnérabilités et d&#39;autres ne sont pas introduites intentionnellement, mais quoi qu&#39;il en soit, un code de contrat intelligent indésirable entraîne évidemment une perte de fonds inattendue pour les utilisateurs d&#39;Ethereum, et ce n&#39;est pas idéal. Vyper est conçu pour faciliter l&#39;écriture de code sécurisé, ou également pour rendre plus difficile l&#39;écriture accidentelle de code trompeur ou vulnérable.

[[comparison_to_solidity_sec]]
=== Comparaison avec Solidity

(((&quot;Solidity&quot;,&quot;Vyper par rapport à&quot;, id=&quot;ix_08smart-contracts-vyper-asciidoc1&quot;, range=&quot;startofrange&quot;)))(((&quot;Vyper&quot;,&quot;Solidity par rapport à&quot;, id=&quot;ix_08smart -contracts-vyper-asciidoc2&quot;, range=&quot;startofrange&quot;)))L&#39;une des façons dont Vyper essaie de rendre le code dangereux plus difficile à écrire est en _omettant_ délibérément certaines fonctionnalités de Solidity. Il est important pour ceux qui envisagent de développer des contrats intelligents dans Vyper de comprendre quelles fonctionnalités Vyper n&#39;a _pas_, et pourquoi. Par conséquent, dans cette section, nous allons explorer ces fonctionnalités et expliquer pourquoi elles ont été omises.

==== Modificateurs

(((&quot;modificateurs&quot;)))(((&quot;Solidity&quot;,&quot;modificateurs&quot;)))(((&quot;Vyper&quot;,&quot;modificateurs&quot;)))Comme nous l&#39;avons vu dans le chapitre précédent, dans Solidity vous pouvez écrire une fonction à l&#39;aide de modificateurs (modifiers). Par exemple, la fonction suivante, `changeOwner`, exécutera le code dans un modificateur appelé `onlyBy` dans le cadre de son exécution :

[source,javascript]
----
function changeOwner(address _newOwner)
    public
    onlyBy(owner)
{
    owner = _newOwner;
}
----

Ce modificateur applique une règle relative à la propriété. Comme vous pouvez le voir, ce modificateur particulier agit comme un mécanisme pour effectuer une pré-vérification au nom de la fonction `changeOwner` :

[source,javascript]
----
modifier onlyBy(address _account)
{
    require(msg.sender == _account);
    _;
}
----

Mais les modificateurs ne sont pas là uniquement pour effectuer des vérifications, comme illustré ici. En fait, en tant que modificateurs, ils peuvent modifier considérablement l&#39;environnement d&#39;un contrat intelligent, dans le contexte de la fonction appelante. En termes simples, les modificateurs sont _omniprésents_.

Regardons un autre exemple de style Solidity :

[source, javascript]
----
enum Stages {
    SafeStage,
    DangerStage,
    FinalStage
}

uint public creationTime = now;
Stages public stage = Stages.SafeStage;

function nextStage() internal {
    stage = Stages(uint(stage) + 1);
}

modifier stageTimeConfirmation() {
    if (stage == Stages.SafeStage &&
                now >= creationTime + 10 days)
        nextStage();
    _;
}

function a()
    public
    stageTimeConfirmation
// Plus de code va ici
{
}
----

D&#39;une part, les développeurs doivent toujours vérifier tout autre code que leur propre code appelle. Cependant, il est possible que dans certaines situations (comme lorsque les contraintes de temps ou l&#39;épuisement entraînent un manque de concentration), un développeur oublie une seule ligne de code. Cela est encore plus probable si le développeur doit se déplacer dans un fichier volumineux tout en gardant mentalement une trace de la hiérarchie des appels de fonction et en mémorisant l&#39;état des variables de contrat intelligent.

Regardons l&#39;exemple précédent un peu plus en profondeur. Imaginez qu&#39;un développeur écrive une fonction publique appelée &quot;a&quot;. Le développeur est nouveau dans ce contrat et utilise un modificateur écrit par quelqu&#39;un d&#39;autre. En un coup d&#39;œil, il semble que le modificateur `stageTimeConfirmation` effectue simplement quelques vérifications concernant l&#39;âge du contrat par rapport à la fonction appelante. Ce que le développeur peut _ne pas_ réaliser, c&#39;est que le modificateur appelle également une autre fonction, `nextStage`. Dans ce scénario de démonstration simpliste, le simple fait d&#39;appeler la fonction publique &quot;a&quot; entraîne le déplacement de la variable &quot;stage&quot; du contrat intelligent de &quot;SafeStage&quot; à &quot;DangerStage&quot;.

Vyper a complètement supprimé les modificateurs. Les recommandations de Vyper sont les suivantes : si vous n&#39;exécutez que des assertions avec des modificateurs, utilisez simplement des vérifications et des assertions en ligne dans le cadre de la fonction ; si vous modifiez l&#39;état du contrat intelligent, etc., intégrez à nouveau ces modifications explicitement à la fonction. Cela améliore l&#39;auditabilité et la lisibilité, car le lecteur n&#39;a pas à &quot;envelopper&quot; mentalement (ou manuellement) le code du modificateur autour de la fonction pour voir ce qu&#39;elle fait.

==== Héritage de classe

(((&quot;héritage de classe&quot;)))(((&quot;héritage&quot;)))(((&quot;Solidity&quot;,&quot;héritage de classe&quot;)))(((&quot;Vyper&quot;,&quot;héritage de classe&quot;)))L&#39;héritage permet aux programmeurs pour exploiter la puissance du code pré-écrit en acquérant des fonctionnalités, des propriétés et des comportements préexistants à partir de bibliothèques de logiciels existantes. L&#39;héritage est puissant et favorise la réutilisation du code. Solidity prend en charge l&#39;héritage multiple ainsi que le polymorphisme, mais bien que ce soient des fonctionnalités clés de la programmation orientée objet, Vyper ne les prend pas en charge. Vyper soutient que la mise en œuvre de l&#39;héritage nécessite que les codeurs et les auditeurs sautent entre plusieurs fichiers afin de comprendre ce que fait le programme. Vyper considère également que l&#39;héritage multiple peut rendre le code trop compliqué à comprendre - un point de vue tacitement admis par la http://bit.ly/2Q6Azvo[documentation] Solidity, qui donne un exemple de la façon dont l&#39;héritage multiple peut être problématique.

==== Assemblage en ligne

(((&quot;assemblage en ligne&quot;)))(((&quot;assemblage en ligne&quot;,&quot;Solidité par rapport à Vyper&quot;)))(((&quot;Assemblage en ligne de solidité&quot;)))L&#39;assemblage en ligne donne aux développeurs un accès de bas niveau à Ethereum Virtual Machine, permettant aux programmes Solidity d&#39;effectuer des opérations en accédant directement aux instructions EVM. Par exemple, le code assembleur en ligne suivant ajoute 3 à l&#39;emplacement mémoire +0x80+ :

----
3 0x80 mload add 0x80 mstore
----

Vyper considère que la perte de lisibilité est un prix trop élevé à payer pour la puissance supplémentaire et ne prend donc pas en charge l&#39;assemblage en ligne.

==== Surcharge de fonction

(((&quot;surcharge de fonction&quot;)))(((&quot;Solidity&quot;,&quot;surcharge de fonction&quot;)))(((&quot;Vyper&quot;,&quot;surcharge de fonction&quot;)))La surcharge de fonction permet aux développeurs d&#39;écrire plusieurs fonctions du même nom. La fonction utilisée à une occasion donnée dépend des types d&#39;arguments fournis. Prenons par exemple les deux fonctions suivantes :

[source,javascript]
----
function f(uint _in) public pure returns (uint out) {
    out = 1;
}

function f(uint _in, bytes32 _key) public pure returns (uint out) {
    out = 2;
}
----

La première fonction (nommée +f+) accepte un argument d&#39;entrée de type +uint+ ; la deuxième fonction (également nommée +f+) accepte deux arguments, un de type +uint+ et un de type +bytes32+. Avoir plusieurs définitions de fonction avec le même nom prenant des arguments différents peut être déroutant, donc Vyper ne prend pas en charge la surcharge de fonction.

==== Conversion de type variable

(((&quot;Solidity&quot;,&quot;transtypage de variable&quot;)))(((&quot;transtypage&quot;)))(((&quot;Vyper&quot;,&quot;transtypage de variable&quot;)))Il existe deux types de typage : _implicit_ et _explicit_

(((&quot;transtypage implicite&quot;)))Le transtypage implicite est souvent effectué au moment de la compilation. Par exemple, si une conversion de type est sémantiquement correcte et qu&#39;aucune information n&#39;est susceptible d&#39;être perdue, le compilateur peut effectuer une conversion implicite, telle que la conversion d&#39;une variable de type +uint8+ en +uint16+. Les premières versions de Vyper autorisaient le transtypage implicite des variables, mais pas les versions récentes.

(((&quot;transtypage explicite&quot;)))Les transtypages explicites peuvent être insérés dans Solidity. Malheureusement, ils peuvent entraîner des comportements inattendus. Par exemple, convertir un +uint32+ en un type plus petit +uint16+ supprime simplement les bits d&#39;ordre supérieur, comme illustré ici :

[source,javascript]
----
uint32 a = 0x12345678;
uint16 b = uint16(a);
// La variable b est 0x5678 maintenant
----

(((&quot;fonction convert (Vyper)&quot;)))Vyper a à la place une fonction +convert+ pour effectuer des transtypages explicites. La fonction convert (trouvée à la ligne 82 de http://bit.ly/2P36ZKT[_convert.py_]) :

[source,python]
----
def convert(expr, context):
    output_type = expr.args[1].s
    if output_type in conversion_table:
        return conversion_table[output_type](expr, context)
    else:
        raise Exception("Conversion to {} is invalid.".format(output_type))
----

Notez l&#39;utilisation de +conversion_table+ (trouvé à la ligne 90 du même fichier), qui ressemble à ceci :

[source,python]
----
conversion_table = {
    'int128': to_int128,
    'uint256': to_unint256,
    'decimal': to_decimal,
    'bytes32': to_bytes32,
}
----

Lorsqu&#39;un développeur appelle +convert+, il fait référence à +conversion_table+, ce qui garantit que la conversion appropriée est effectuée. Par exemple, si un développeur passe un +int128+ à la fonction +convert+, la fonction +to_int128+ à la ligne 26 du même fichier (_convert.py_) sera exécutée. La fonction +to_int128+ est la suivante :

[source,python]
----
@signature(('int128', 'uint256', 'bytes32', 'bytes'), 'str_literal')
def to_int128(expr, args, kwargs, context):
    in_node = args[0]
    typ, len = get_type(in_node)
    if typ in ('int128', 'uint256', 'bytes32'):
        if in_node.typ.is_literal 
            and not SizeLimits.MINNUM <= in_node.value <= SizeLimits.MAXNUM:
            raise InvalidLiteralException(
                "Number out of range: {}".format(in_node.value), expr
            )
        return LLLnode.from_list(
            ['clamp', ['mload', MemoryPositions.MINNUM], in_node,
            ['mload', MemoryPositions.MAXNUM]], typ=BaseType('int128'),
            pos=getpos(expr)
        )
    else:
        return byte_array_to_num(in_node, expr, 'int128')
----

Comme vous pouvez le constater, le processus de conversion garantit qu&#39;aucune information ne peut être perdue. si c&#39;est possible, une exception est levée. Le code de conversion empêche la troncation ainsi que d&#39;autres anomalies qui seraient normalement autorisées par un transtypage implicite.

Choisir un transtypage explicite plutôt qu&#39;implicite signifie que le développeur est responsable de l&#39;exécution de tous les transtypages. Bien que cette approche produise un code plus détaillé, elle améliore également la sécurité et la vérifiabilité des contrats intelligents.


==== Préconditions et Postconditions

(((&quot;Vyper&quot;,&quot;préconditions/postconditions&quot;)))Vyper gère explicitement les préconditions, les postconditions et les changements d&#39;état. Bien que cela produise un code redondant, cela permet également une lisibilité et une sécurité maximales. Lors de la rédaction d&#39;un contrat intelligent dans Vyper, un développeur doit observer les trois points suivants :

Condition::
Quel est l&#39;état/condition actuel des variables d&#39;état Ethereum ?
Effets::
Quels effets ce code de contrat intelligent aura-t-il sur la condition des variables d&#39;état lors de l&#39;exécution ? Autrement dit, qu&#39;est-ce qui sera affecté et qu&#39;est-ce qui ne sera pas affecté ? Ces effets sont-ils conformes aux intentions du contrat intelligent ?
Interaction::
Une fois que les deux premières considérations ont été traitées de manière exhaustive, il est temps d&#39;exécuter le code. Avant le déploiement, parcourez logiquement le code et examinez tous les résultats permanents possibles, les conséquences et les scénarios d&#39;exécution du code, y compris les interactions avec d&#39;autres contrats.

Idéalement, chacun de ces points devrait être soigneusement examiné puis documenté de manière approfondie dans le code. Cela améliorera la conception du code, le rendant finalement plus lisible et auditable.(((range=&quot;endofrange&quot;, startref=&quot;ix_08smart-contracts-vyper-asciidoc2&quot;)))(((range=&quot;endofrange&quot;, startref=&quot;ix_08smart-contracts-vyper-asciidoc1&quot;)))

[[decorators_sec]]
=== Décorateurs
(((&quot;décorateurs, Vyper&quot;)))(((&quot;Vyper&quot;,&quot;décorateurs&quot;)))Les décorateurs suivants peuvent être utilisés au début de chaque fonction :

+@private+ :: Le décorateur `@private` rend la fonction inaccessible depuis l&#39;extérieur du contrat.

+@public+ :: Le décorateur `@public` rend la fonction à la fois visible et exécutable publiquement. Par exemple, même le portefeuille Ethereum affichera de telles fonctions lors de la visualisation du contrat.

+@constant+ :: Les fonctions avec le décorateur `@constant` ne sont pas autorisées à modifier les variables d&#39;état. En fait, le compilateur rejettera le programme entier (avec une erreur appropriée) si la fonction essaie de changer une variable d&#39;état.

+@payable+ :: Seules les fonctions avec le décorateur `@payable` sont autorisées à transférer de la valeur.

Vyper implémente explicitement http://bit.ly/2P14RDq[la logique des décorateurs]. Par exemple, le processus de compilation de Vyper échouera si une fonction a à la fois un décorateur `@payable` et un décorateur `@constant`. Cela a du sens car une fonction qui transfère une valeur a par définition mis à jour l&#39;état, elle ne peut donc pas être `@constant`. Chaque fonction Vyper doit être décorée avec `@public` ou `@private` (mais pas les deux !).

[[order_of_functions_sec]]
=== Ordre des fonctions et des variables

(((&quot;déclarations de fonction, ordre de&quot;)))(((&quot;Solidity&quot;,&quot;ordre de fonction&quot;)))(((&quot;Solidity&quot;,&quot;ordre de variable&quot;)))(((&quot;déclarations de variable, ordre de &quot;)))(((&quot;Vyper&quot;,&quot;ordre des fonctions&quot;)))(((&quot;Vyper&quot;,&quot;ordre des variables&quot;)))Chaque contrat intelligent Vyper individuel se compose d&#39;un seul fichier Vyper uniquement. En d&#39;autres termes, tout le code d&#39;un contrat intelligent Vyper donné, y compris toutes les fonctions, variables, etc., existe au même endroit. Vyper exige que la fonction et les déclarations de variables de chaque contrat intelligent soient écrites physiquement dans un ordre particulier. Solidity n&#39;a pas du tout cette exigence. Jetons un coup d&#39;œil à un exemple Solidity :

[source,javascript]
----
pragma solidity ^0.4.0;

contract ordering {

    function topFunction()
    external
    returns (bool) {
        initiatizedBelowTopFunction = this.lowerFunction();
        return initiatizedBelowTopFunction;
    }

    bool initiatizedBelowTopFunction;
    bool lowerFunctionVar;

    function lowerFunction()
    external
    returns (bool) {
        lowerFunctionVar = true;
        return lowerFunctionVar;
    }

}
----

Dans cet exemple, la fonction appelée +topFunction+ appelle une autre fonction, +lowerFunction+. +topFunction+ attribue également une valeur à une variable appelée +initiatizedBelowTopFunction+. Comme vous pouvez le voir, Solidity n&#39;exige pas que ces fonctions et variables soient physiquement déclarées avant d&#39;être appelées par le code d&#39;exécution. Il s&#39;agit d&#39;un code Solidity valide qui se compilera avec succès.

Les exigences de commande de Vyper ne sont pas une nouveauté ; en fait, ces exigences de commande ont toujours été présentes dans la programmation Python. La commande requise par Vyper est simple et logique, comme illustré dans cet exemple suivant :

[source,python]
----
# Déclarez une variable appelée theBool
theBool: public(bool)

# Déclarez une fonction appelée topFunction
@public
def topFunction() -> bool:
# Attribuez une valeur à la fonction déjà déclarée appelée theBool
    self.theBool = True
    return self.theBool

# Déclarez une fonction appelée lowerFunction
@public
def lowerFunction():
# Appelez la fonction déjà déclarée appelée topFunction
    assert self.topFunction()
----

Cela montre le bon ordre des fonctions et des variables dans un contrat intelligent Vyper. Notez comment la variable +theBool+ et la fonction +topFunction+ sont déclarées avant qu&#39;elles ne reçoivent une valeur et ne soient appelées, respectivement. Si +theBool+ était déclaré sous +topFunction+ ou si +topFunction+ était déclaré sous +lowerFunction+, ce contrat ne serait pas compilé.

[[online_code_editor_and_compiler_sec]]
=== Compilation
(((&quot;compilation&quot;,&quot;Vyper&quot;)))(((&quot;Vyper&quot;,&quot;compilation&quot;)))Vyper a son propre https://vyper.online[éditeur de code et compilateur en ligne], qui vous permet d&#39;écrire puis compilez vos contrats intelligents en bytecode, ABI et LLL en utilisant uniquement votre navigateur Web. Le compilateur en ligne Vyper propose une variété de contrats intelligents pré-écrits pour votre commodité, y compris des contrats pour une simple enchère ouverte, des achats à distance sécurisés, des jetons ERC20, etc. Cet outil, propose une seule version du logiciel de compilation. Il est mis à jour régulièrement mais ne garantit pas toujours la dernière version. Etherscan a un https://etherscan.io/vyper[compilateur Vyper en ligne] qui vous permet de sélectionner la version du compilateur. De plus, https://remix.ethereum.org[Remix], conçu à l&#39;origine pour les contrats intelligents Solidity, dispose désormais d&#39;un plug-in Vyper disponible dans l&#39;onglet Paramètres.

[NOTE]
====
(((&quot;jeton standard ERC20&quot;,&quot;implementation Vyper  de&quot;)))Vyper implémente ERC20 en tant que contrat précompilé, ce qui permet d&#39;utiliser facilement ces contrats intelligents prêts à l&#39;emploi. Les contrats dans Vyper doivent être déclarés en tant que variables globales. Un exemple de déclaration de la variable ERC20 est le suivant :

[source,javascript]
----
token: address(ERC20)
----
====

Vous pouvez également compiler un contrat à l&#39;aide de la ligne de commande. Chaque contrat Vyper est enregistré dans un seul fichier avec l&#39;extension _.vy_.
Une fois installé, vous pouvez compiler un contrat avec Vyper en exécutant la commande suivante :

----
vyper ~/hello_world.vy
----

La description ABI lisible par l&#39;homme (au format JSON) peut ensuite être obtenue en exécutant la commande suivante :

----
vyper -f json ~/hello_world.v.py
----

[[protecting_against_overflows_sec]]
=== Protection contre les erreurs de débordement au niveau du compilateur

(((&quot;compilation&quot;,&quot;protection contre les erreurs de débordement au niveau du compilateur&quot;)))(((&quot;débordement&quot;,&quot;protection contre le&quot;)))(((&quot;Vyper&quot;,&quot;protection contre le débordement&quot;)))Les erreurs de débordement dans le logiciel peut être catastrophique lorsqu&#39;il s&#39;agit de valeur réelle. Par exemple, une http://bit.ly/2yHfvoF[transaction de la mi-avril 2018] montre le pass:[<span class="keep-together">transfert malveillant de plus de 57 896 044 618 658 100 000 000 000 000 000 000 000 000,</span>]000 000 000 000 000 000 tokens ou jetons BEC. Cette transaction était le résultat d&#39;un problème de débordement d&#39;entier dans le contrat de jeton ERC20 de BeautyChain (_BecToken.sol_). Les développeurs de Solidity ont accès à des bibliothèques comme http://bit.ly/2ABhb4l[+SafeMath+] ainsi qu&#39;à des outils d&#39;analyse de la sécurité des contrats intelligents Ethereum comme http://bit.ly/2CQRoGU[Mythril OSS]. Cependant, les développeurs ne sont pas obligés d&#39;utiliser les outils de sécurité. En termes simples, si la sécurité n&#39;est pas appliquée par le langage, les développeurs peuvent écrire du code non sécurisé qui se compilera avec succès et s&#39;exécutera plus tard &quot;avec succès&quot;.

Vyper dispose d&#39;une protection intégrée contre les débordements, mise en œuvre selon une approche à deux volets. Tout d&#39;abord, Vyper fournit http://bit.ly/2PuDfpB[un +SafeMath+ équivalent] qui inclut les cas d&#39;exception nécessaires pour l&#39;arithmétique entière. Deuxièmement, Vyper utilise des pinces chaque fois qu&#39;une constante littérale est chargée, qu&#39;une valeur est transmise à une fonction ou qu&#39;une variable est affectée. Les pinces sont implémentées via des fonctions personnalisées dans le compilateur LLL (Low-level Lisp-like Language) et ne peuvent pas être désactivées. (Le compilateur Vyper génère LLL plutôt que le bytecode EVM ; cela simplifie le développement de Vyper lui-même.)


[[reading_and_writing_data_sec]]
=== Lecture et écriture de données
(((&quot;Vyper&quot;,&quot;lecture/écriture de données&quot;)))Bien qu&#39;il soit coûteux de stocker, lire et modifier des données, ces opérations de stockage sont une composante nécessaire de la plupart des contrats intelligents. Les contrats intelligents peuvent écrire des données à deux endroits :

État global:: (((&quot;Global State trie&quot;))) Les variables d&#39;état d&#39;un contrat intelligent donné sont stockées dans le trie d&#39;état global d&#39;Ethereum ; un contrat intelligent ne peut stocker, lire et modifier que des données relatives à l&#39;adresse de ce contrat particulier (c&#39;est-à-dire que les contrats intelligents ne peuvent pas lire ou écrire dans d&#39;autres contrats intelligents).

Journaux:: (((&quot;journaux, Vyper&quot;)))Un contrat intelligent peut également écrire dans les données de la chaîne d&#39;Ethereum via des événements de journal. Alors que Vyper utilisait initialement la syntaxe pass:[<code>__log__</code>] pour déclarer ces événements, une mise à jour a été effectuée pour aligner davantage sa déclaration d&#39;événement sur la syntaxe d&#39;origine de Solidity. Par exemple, la déclaration par Vyper d&#39;un événement appelé `MyLog` était à l&#39;origine `MyLog: pass:[__]logpass:[__]({arg1: indexed(bytes[3])})`. La syntaxe est maintenant devenue `MyLog: event({arg1: indexed(bytes[3])})`. Il est important de noter que l&#39;exécution de l&#39;événement de journalisation dans Vyper était, et est toujours, comme suit : `log.MyLog(&quot;123&quot;)`.

Bien que les contrats intelligents puissent écrire dans les données de la chaîne d&#39;Ethereum (via des événements de journal), ils ne peuvent pas lire les événements de journal en chaîne qu&#39;ils ont créés. Néanmoins, l&#39;un des avantages de l&#39;écriture dans les données de la chaîne d&#39;Ethereum via des événements de journal est que les journaux peuvent être découverts et lus, sur la chaîne publique, par des clients légers. Par exemple, la valeur +logsBloom+ dans un bloc extrait peut indiquer si un événement de journal est présent ou non. Une fois que l&#39;existence d&#39;événements de journal a été établie, les données de journal peuvent être obtenues à partir d&#39;un reçu de transaction donné.


=== Conclusion

Vyper est un nouveau langage de programmation orienté contrat puissant et intéressant. Sa conception est biaisée vers &quot;l&#39;exactitude&quot;, au détriment d&#39;une certaine flexibilité. Cela peut permettre aux programmeurs de rédiger de meilleurs contrats intelligents et d&#39;éviter certains pièges qui provoquent l&#39;apparition de graves vulnérabilités. Ensuite, nous examinerons plus en détail la sécurité des contrats intelligents. Certaines des nuances de la conception de Vyper peuvent devenir plus apparentes une fois que vous avez lu tous les problèmes de sécurité possibles qui peuvent survenir dans les contrats intelligents.(((range=&quot;endofrange&quot;, startref=&quot;ix_08smart-contracts-vyper-asciidoc0&quot;)))